#端口号
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: c123
    url: jdbc:mysql://localhost:3306/tb_app?useSSL=false&serverTimezone=UTC
  main:
    banner-mode: off
#日志
logging:
  level:
    root: warn
mybatis-plus:
  global-config:
    banner: off
#  configuration:
#    map-underscore-to-camel-case: false
jwt:
  token:
    header: Authorization
    expire: 604800
    secrst: qodkvjeifksivjdugjdkendjjddjnsfr
